# Generated by Django 5.1.4 on 2025-04-03 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='empty title', max_length=100)),
                ('content', models.TextField(default='empty content')),
                ('summary', models.TextField(default='empty summary')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('origin_url', models.URLField(blank=True, unique=True)),
                ('tts_content', models.TextField(default='empty tts content')),
                ('tts_url', models.URLField(blank=True)),
            ],
        ),
    ]
