# Generated by Django 5.1.4 on 2024-12-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trandlator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='tickers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='trandlator.ticker'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='courses', to='trandlator.article'),
        ),
    ]
