# Generated by Django 5.1.4 on 2025-04-03 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_name', models.CharField(max_length=100, unique=True)),
                ('last_price', models.FloatField(default=0)),
                ('before_last_price', models.FloatField(default=0)),
                ('price_diff', models.FloatField(default=0)),
                ('percentage_diff', models.FloatField(default=0)),
                ('last_price_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('before_last_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('articles', models.ManyToManyField(blank=True, related_name='tickers', to='article.article')),
            ],
        ),
    ]
