# Generated by Django 5.1.4 on 2025-03-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trandlator', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mail_frequency', models.CharField(default='everyday', max_length=20)),
                ('mail_timeSlot', models.CharField(default='onceDay', max_length=20)),
                ('mail_newsCount', models.CharField(default='oneNews', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('tickers', models.ManyToManyField(blank=True, related_name='users', to='trandlator.ticker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
